export const boothStyles = {
  container: "min-h-screen bg-stone-900 flex flex-col items-center justify-center py-10 px-4",
  header: "text-4xl text-white font-mono mb-6 tracking-widest",
  controlsContainer: "flex flex-col items-center gap-6",
  filterContainer: "flex gap-3 flex-wrap justify-center bg-stone-800 p-3 rounded-full",
  filterButton: (isActive) => `px-4 py-2 rounded-full text-sm font-bold transition-all ${isActive ? 'bg-pink-600 text-white shadow-lg scale-105' : 'bg-stone-700 text-gray-300 hover:bg-stone-600'}`,
  cameraWrapper: "relative border-8 border-stone-700 rounded-2xl overflow-hidden shadow-2xl",
  webcam: "w-96 h-96 object-cover",
  flashOverlay: (active) => `absolute inset-0 bg-white pointer-events-none transition-opacity duration-150 ease-out ${active ? 'opacity-100' : 'opacity-0'}`,
  countdownOverlay: "absolute inset-0 flex items-center justify-center bg-black/40 backdrop-blur-sm",
  countdownText: "text-9xl text-white font-bold animate-ping drop-shadow-lg",
  startButton: "absolute bottom-6 left-1/2 -translate-x-1/2 bg-linear-to-r from-pink-600 to-purple-600 hover:from-pink-700 hover:to-purple-700 text-white px-10 py-4 rounded-full font-bold shadow-xl transition transform hover:scale-105 tracking-wider",
  reviewContainer: "flex flex-col items-center gap-8 animate-fadeIn",
  stripWrapper: "bg-pink-50 p-6 pb-10 shadow-2xl rotate-1 transform border-4 border-double border-pink-400",
  stripHeader: "text-center font-mono text-2xl text-pink-700 mb-6 tracking-widest font-bold",
  stripImages: "flex flex-col gap-5",
  stripImage: "w-full h-72 object-cover rounded-sm border border-gray-200 shadow-sm",
  stripFooter: "text-center mt-6",
  footerTitle: "font-mono text-lg tracking-widest text-gray-700 uppercase",
  footerDate: "text-sm text-gray-500",
  actionsContainer: "flex flex-col items-center gap-4",
  savingText: "text-pink-400 animate-pulse",
  savedText: "text-green-400 text-xl font-bold animate-bounce",
  buttonGroup: "flex gap-4",
  btnNew: "px-6 py-3 bg-stone-700 text-white rounded-full font-bold hover:bg-stone-600 shadow-lg transition",
  btnDownload: "px-8 py-3 bg-linear-to-r from-pink-600 to-purple-600 text-white rounded-full font-bold hover:opacity-90 shadow-lg transition animate-pulse",
};

export const memoryStyles = {
  container: "w-full bg-stone-100 py-20 overflow-hidden",
  header: "text-4xl md:text-6xl font-bold text-center text-stone-700 mb-20",
  grid: "max-w-6xl mx-auto px-4",
  section: (index) => `memory-section flex flex-col md:flex-row items-center gap-10 mb-32 ${index % 2 !== 0 ? 'md:flex-row-reverse' : ''}`,
  imgWrapper: "w-full md:w-1/2",
  imgContainer: "relative group overflow-hidden rounded-2xl shadow-xl transform rotate-2 hover:rotate-0 transition-all duration-500",
  img: "w-full h-auto object-cover",
  textWrapper: "w-full md:w-1/2 space-y-4 text-center md:text-left",
  dateTag: "inline-block px-4 py-1 bg-pink-200 text-pink-800 rounded-full text-sm font-semibold",
  title: "text-3xl font-bold text-stone-800",
  description: "text-lg text-stone-600 leading-relaxed",
};